/**
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.uCdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getStartFrom <em>Start From</em>}</li>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getName <em>Name</em>}</li>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getCondition <em>Condition</em>}</li>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getSteps <em>Steps</em>}</li>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getResumeAt <em>Resume At</em>}</li>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension()
 * @model
 * @generated
 */
public interface Extension extends EObject
{
  /**
   * Returns the value of the '<em><b>Start From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start From</em>' reference.
   * @see #setStartFrom(Step)
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_StartFrom()
   * @model
   * @generated
   */
  Step getStartFrom();

  /**
   * Sets the value of the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getStartFrom <em>Start From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start From</em>' reference.
   * @see #getStartFrom()
   * @generated
   */
  void setStartFrom(Step value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_Steps()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionStep> getSteps();

  /**
   * Returns the value of the '<em><b>Resume At</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resume At</em>' reference.
   * @see #setResumeAt(Step)
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_ResumeAt()
   * @model
   * @generated
   */
  Step getResumeAt();

  /**
   * Sets the value of the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getResumeAt <em>Resume At</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resume At</em>' reference.
   * @see #getResumeAt()
   * @generated
   */
  void setResumeAt(Step value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(DeadEndStep)
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getExtension_End()
   * @model containment="true"
   * @generated
   */
  DeadEndStep getEnd();

  /**
   * Sets the value of the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(DeadEndStep value);

} // Extension
