/**
 * generated by Xtext 2.22.0
 */
package ucwriter.xtext.guimeta.ucdsl.uCdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslFactory
 * @model kind="package"
 * @generated
 */
public interface UCdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "uCdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.ucwriter/guimeta/ucdsl/UCdsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "uCdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UCdslPackage eINSTANCE = ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl.init();

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseDocumentImpl <em>Use Case Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseDocumentImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCaseDocument()
   * @generated
   */
  int USE_CASE_DOCUMENT = 0;

  /**
   * The feature id for the '<em><b>Usecase</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DOCUMENT__USECASE = 0;

  /**
   * The number of structural features of the '<em>Use Case Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DOCUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseImpl <em>Use Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCase()
   * @generated
   */
  int USE_CASE = 1;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NAME = 1;

  /**
   * The feature id for the '<em><b>Precondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__PRECONDITION = 2;

  /**
   * The feature id for the '<em><b>Postcondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__POSTCONDITION = 3;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__STEPS = 4;

  /**
   * The feature id for the '<em><b>Alternativeflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__ALTERNATIVEFLOWS = 5;

  /**
   * The number of structural features of the '<em>Use Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionImpl <em>Extension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtension()
   * @generated
   */
  int EXTENSION = 2;

  /**
   * The feature id for the '<em><b>Start From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__START_FROM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__NAME = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__CONDITION = 2;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__STEPS = 3;

  /**
   * The feature id for the '<em><b>Resume At</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__RESUME_AT = 4;

  /**
   * The feature id for the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION__END = 5;

  /**
   * The number of structural features of the '<em>Extension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.StepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getStep()
   * @generated
   */
  int STEP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__NAME = 0;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__REFERENCE = 1;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseStepImpl <em>Use Case Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCaseStep()
   * @generated
   */
  int USE_CASE_STEP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_STEP__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_STEP__REFERENCE = STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_STEP__PARENT = STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Use Case Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_STEP_FEATURE_COUNT = STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionStepImpl <em>Extension Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtensionStep()
   * @generated
   */
  int EXTENSION_STEP = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__REFERENCE = STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP__SENTENCE = STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Extension Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_STEP_FEATURE_COUNT = STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.DeadEndStepImpl <em>Dead End Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.DeadEndStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getDeadEndStep()
   * @generated
   */
  int DEAD_END_STEP = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEAD_END_STEP__NAME = EXTENSION_STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEAD_END_STEP__REFERENCE = EXTENSION_STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEAD_END_STEP__SENTENCE = EXTENSION_STEP__SENTENCE;

  /**
   * The number of structural features of the '<em>Dead End Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEAD_END_STEP_FEATURE_COUNT = EXTENSION_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PreconditionImpl <em>Precondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PreconditionImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getPrecondition()
   * @generated
   */
  int PRECONDITION = 7;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Precondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PostconditionImpl <em>Postcondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PostconditionImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getPostcondition()
   * @generated
   */
  int POSTCONDITION = 8;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Postcondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensioConditionImpl <em>Extensio Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensioConditionImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtensioCondition()
   * @generated
   */
  int EXTENSIO_CONDITION = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSIO_CONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Extensio Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSIO_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingConditionImpl <em>Repeating Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingConditionImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getRepeatingCondition()
   * @generated
   */
  int REPEATING_CONDITION = 10;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_CONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Repeating Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UserStepImpl <em>User Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UserStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUserStep()
   * @generated
   */
  int USER_STEP = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP__NAME = USE_CASE_STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP__REFERENCE = USE_CASE_STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP__PARENT = USE_CASE_STEP__PARENT;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP__SENTENCE = USE_CASE_STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>User Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP_FEATURE_COUNT = USE_CASE_STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.SystemStepImpl <em>System Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.SystemStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getSystemStep()
   * @generated
   */
  int SYSTEM_STEP = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP__NAME = USE_CASE_STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP__REFERENCE = USE_CASE_STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP__PARENT = USE_CASE_STEP__PARENT;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP__SENTENCE = USE_CASE_STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>System Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP_FEATURE_COUNT = USE_CASE_STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingStepImpl <em>Repeating Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingStepImpl
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getRepeatingStep()
   * @generated
   */
  int REPEATING_STEP = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP__NAME = USE_CASE_STEP__NAME;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP__REFERENCE = USE_CASE_STEP__REFERENCE;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP__PARENT = USE_CASE_STEP__PARENT;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP__CONDITION = USE_CASE_STEP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP__STEPS = USE_CASE_STEP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Repeating Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEATING_STEP_FEATURE_COUNT = USE_CASE_STEP_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument <em>Use Case Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Document</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument
   * @generated
   */
  EClass getUseCaseDocument();

  /**
   * Returns the meta object for the containment reference list '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument#getUsecase <em>Usecase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Usecase</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument#getUsecase()
   * @see #getUseCaseDocument()
   * @generated
   */
  EReference getUseCaseDocument_Usecase();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase
   * @generated
   */
  EClass getUseCase();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getNumber()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Number();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getName()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Name();

  /**
   * Returns the meta object for the containment reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getPrecondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Precondition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getPrecondition()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Precondition();

  /**
   * Returns the meta object for the containment reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getPostcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Postcondition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getPostcondition()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Postcondition();

  /**
   * Returns the meta object for the containment reference list '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getSteps()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Steps();

  /**
   * Returns the meta object for the containment reference list '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getAlternativeflows <em>Alternativeflows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alternativeflows</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase#getAlternativeflows()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Alternativeflows();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension <em>Extension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extension</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension
   * @generated
   */
  EClass getExtension();

  /**
   * Returns the meta object for the reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getStartFrom <em>Start From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Start From</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getStartFrom()
   * @see #getExtension()
   * @generated
   */
  EReference getExtension_StartFrom();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getName()
   * @see #getExtension()
   * @generated
   */
  EAttribute getExtension_Name();

  /**
   * Returns the meta object for the containment reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getCondition()
   * @see #getExtension()
   * @generated
   */
  EReference getExtension_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getSteps()
   * @see #getExtension()
   * @generated
   */
  EReference getExtension_Steps();

  /**
   * Returns the meta object for the reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getResumeAt <em>Resume At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Resume At</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getResumeAt()
   * @see #getExtension()
   * @generated
   */
  EReference getExtension_ResumeAt();

  /**
   * Returns the meta object for the containment reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension#getEnd()
   * @see #getExtension()
   * @generated
   */
  EReference getExtension_End();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Step#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Step#getName()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Name();

  /**
   * Returns the meta object for the reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Step#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Step#getReference()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Reference();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep <em>Use Case Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep
   * @generated
   */
  EClass getUseCaseStep();

  /**
   * Returns the meta object for the reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep#getParent()
   * @see #getUseCaseStep()
   * @generated
   */
  EReference getUseCaseStep_Parent();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep <em>Extension Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extension Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep
   * @generated
   */
  EClass getExtensionStep();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep#getSentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sentence</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep#getSentence()
   * @see #getExtensionStep()
   * @generated
   */
  EAttribute getExtensionStep_Sentence();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.DeadEndStep <em>Dead End Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dead End Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.DeadEndStep
   * @generated
   */
  EClass getDeadEndStep();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Precondition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition
   * @generated
   */
  EClass getPrecondition();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition#getCondition()
   * @see #getPrecondition()
   * @generated
   */
  EAttribute getPrecondition_Condition();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Postcondition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition
   * @generated
   */
  EClass getPostcondition();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition#getCondition()
   * @see #getPostcondition()
   * @generated
   */
  EAttribute getPostcondition_Condition();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensioCondition <em>Extensio Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extensio Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensioCondition
   * @generated
   */
  EClass getExtensioCondition();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensioCondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensioCondition#getCondition()
   * @see #getExtensioCondition()
   * @generated
   */
  EAttribute getExtensioCondition_Condition();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingCondition <em>Repeating Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repeating Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingCondition
   * @generated
   */
  EClass getRepeatingCondition();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingCondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingCondition#getCondition()
   * @see #getRepeatingCondition()
   * @generated
   */
  EAttribute getRepeatingCondition_Condition();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep <em>User Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep
   * @generated
   */
  EClass getUserStep();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep#getSentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sentence</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep#getSentence()
   * @see #getUserStep()
   * @generated
   */
  EAttribute getUserStep_Sentence();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep <em>System Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep
   * @generated
   */
  EClass getSystemStep();

  /**
   * Returns the meta object for the attribute '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep#getSentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sentence</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep#getSentence()
   * @see #getSystemStep()
   * @generated
   */
  EAttribute getSystemStep_Sentence();

  /**
   * Returns the meta object for class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep <em>Repeating Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repeating Step</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep
   * @generated
   */
  EClass getRepeatingStep();

  /**
   * Returns the meta object for the containment reference '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep#getCondition()
   * @see #getRepeatingStep()
   * @generated
   */
  EReference getRepeatingStep_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep#getSteps()
   * @see #getRepeatingStep()
   * @generated
   */
  EReference getRepeatingStep_Steps();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UCdslFactory getUCdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseDocumentImpl <em>Use Case Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseDocumentImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCaseDocument()
     * @generated
     */
    EClass USE_CASE_DOCUMENT = eINSTANCE.getUseCaseDocument();

    /**
     * The meta object literal for the '<em><b>Usecase</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DOCUMENT__USECASE = eINSTANCE.getUseCaseDocument_Usecase();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseImpl <em>Use Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCase()
     * @generated
     */
    EClass USE_CASE = eINSTANCE.getUseCase();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NUMBER = eINSTANCE.getUseCase_Number();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NAME = eINSTANCE.getUseCase_Name();

    /**
     * The meta object literal for the '<em><b>Precondition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__PRECONDITION = eINSTANCE.getUseCase_Precondition();

    /**
     * The meta object literal for the '<em><b>Postcondition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__POSTCONDITION = eINSTANCE.getUseCase_Postcondition();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__STEPS = eINSTANCE.getUseCase_Steps();

    /**
     * The meta object literal for the '<em><b>Alternativeflows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__ALTERNATIVEFLOWS = eINSTANCE.getUseCase_Alternativeflows();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionImpl <em>Extension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtension()
     * @generated
     */
    EClass EXTENSION = eINSTANCE.getExtension();

    /**
     * The meta object literal for the '<em><b>Start From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION__START_FROM = eINSTANCE.getExtension_StartFrom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION__NAME = eINSTANCE.getExtension_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION__CONDITION = eINSTANCE.getExtension_Condition();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION__STEPS = eINSTANCE.getExtension_Steps();

    /**
     * The meta object literal for the '<em><b>Resume At</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION__RESUME_AT = eINSTANCE.getExtension_ResumeAt();

    /**
     * The meta object literal for the '<em><b>End</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTENSION__END = eINSTANCE.getExtension_End();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.StepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__NAME = eINSTANCE.getStep_Name();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__REFERENCE = eINSTANCE.getStep_Reference();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseStepImpl <em>Use Case Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UseCaseStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUseCaseStep()
     * @generated
     */
    EClass USE_CASE_STEP = eINSTANCE.getUseCaseStep();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_STEP__PARENT = eINSTANCE.getUseCaseStep_Parent();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionStepImpl <em>Extension Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtensionStep()
     * @generated
     */
    EClass EXTENSION_STEP = eINSTANCE.getExtensionStep();

    /**
     * The meta object literal for the '<em><b>Sentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_STEP__SENTENCE = eINSTANCE.getExtensionStep_Sentence();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.DeadEndStepImpl <em>Dead End Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.DeadEndStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getDeadEndStep()
     * @generated
     */
    EClass DEAD_END_STEP = eINSTANCE.getDeadEndStep();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PreconditionImpl <em>Precondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PreconditionImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getPrecondition()
     * @generated
     */
    EClass PRECONDITION = eINSTANCE.getPrecondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRECONDITION__CONDITION = eINSTANCE.getPrecondition_Condition();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PostconditionImpl <em>Postcondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.PostconditionImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getPostcondition()
     * @generated
     */
    EClass POSTCONDITION = eINSTANCE.getPostcondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSTCONDITION__CONDITION = eINSTANCE.getPostcondition_Condition();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensioConditionImpl <em>Extensio Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensioConditionImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getExtensioCondition()
     * @generated
     */
    EClass EXTENSIO_CONDITION = eINSTANCE.getExtensioCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSIO_CONDITION__CONDITION = eINSTANCE.getExtensioCondition_Condition();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingConditionImpl <em>Repeating Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingConditionImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getRepeatingCondition()
     * @generated
     */
    EClass REPEATING_CONDITION = eINSTANCE.getRepeatingCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPEATING_CONDITION__CONDITION = eINSTANCE.getRepeatingCondition_Condition();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UserStepImpl <em>User Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UserStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getUserStep()
     * @generated
     */
    EClass USER_STEP = eINSTANCE.getUserStep();

    /**
     * The meta object literal for the '<em><b>Sentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_STEP__SENTENCE = eINSTANCE.getUserStep_Sentence();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.SystemStepImpl <em>System Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.SystemStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getSystemStep()
     * @generated
     */
    EClass SYSTEM_STEP = eINSTANCE.getSystemStep();

    /**
     * The meta object literal for the '<em><b>Sentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_STEP__SENTENCE = eINSTANCE.getSystemStep_Sentence();

    /**
     * The meta object literal for the '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingStepImpl <em>Repeating Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.RepeatingStepImpl
     * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.UCdslPackageImpl#getRepeatingStep()
     * @generated
     */
    EClass REPEATING_STEP = eINSTANCE.getRepeatingStep();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPEATING_STEP__CONDITION = eINSTANCE.getRepeatingStep_Condition();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPEATING_STEP__STEPS = eINSTANCE.getRepeatingStep_Steps();

  }

} //UCdslPackage
