/**
 * generated by Xtext 2.22.0
 */
package ucwriter.xtext.guimeta.ucdsl.uCdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Case Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument#getUsecase <em>Usecase</em>}</li>
 * </ul>
 *
 * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getUseCaseDocument()
 * @model
 * @generated
 */
public interface UseCaseDocument extends EObject
{
  /**
   * Returns the value of the '<em><b>Usecase</b></em>' containment reference list.
   * The list contents are of type {@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usecase</em>' containment reference list.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage#getUseCaseDocument_Usecase()
   * @model containment="true"
   * @generated
   */
  EList<UseCase> getUsecase();

} // UseCaseDocument
