/**
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.uCdsl.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import ucwriter.xtext.guimeta.ucdsl.uCdsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage
 * @generated
 */
public class UCdslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static UCdslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UCdslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = UCdslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UCdslSwitch<Adapter> modelSwitch =
    new UCdslSwitch<Adapter>()
    {
      @Override
      public Adapter caseUseCaseDocument(UseCaseDocument object)
      {
        return createUseCaseDocumentAdapter();
      }
      @Override
      public Adapter caseUseCase(UseCase object)
      {
        return createUseCaseAdapter();
      }
      @Override
      public Adapter caseExtension(Extension object)
      {
        return createExtensionAdapter();
      }
      @Override
      public Adapter caseStep(Step object)
      {
        return createStepAdapter();
      }
      @Override
      public Adapter caseUseCaseStep(UseCaseStep object)
      {
        return createUseCaseStepAdapter();
      }
      @Override
      public Adapter caseExtensionStep(ExtensionStep object)
      {
        return createExtensionStepAdapter();
      }
      @Override
      public Adapter caseDeadEndStep(DeadEndStep object)
      {
        return createDeadEndStepAdapter();
      }
      @Override
      public Adapter casePrecondition(Precondition object)
      {
        return createPreconditionAdapter();
      }
      @Override
      public Adapter casePostcondition(Postcondition object)
      {
        return createPostconditionAdapter();
      }
      @Override
      public Adapter caseUserStep(UserStep object)
      {
        return createUserStepAdapter();
      }
      @Override
      public Adapter caseSystemStep(SystemStep object)
      {
        return createSystemStepAdapter();
      }
      @Override
      public Adapter caseRepeatingStep(RepeatingStep object)
      {
        return createRepeatingStepAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument <em>Use Case Document</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument
   * @generated
   */
  public Adapter createUseCaseDocumentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCase
   * @generated
   */
  public Adapter createUseCaseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension <em>Extension</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Extension
   * @generated
   */
  public Adapter createExtensionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Step
   * @generated
   */
  public Adapter createStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep <em>Use Case Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseStep
   * @generated
   */
  public Adapter createUseCaseStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep <em>Extension Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep
   * @generated
   */
  public Adapter createExtensionStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.DeadEndStep <em>Dead End Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.DeadEndStep
   * @generated
   */
  public Adapter createDeadEndStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Precondition
   * @generated
   */
  public Adapter createPreconditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.Postcondition
   * @generated
   */
  public Adapter createPostconditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep <em>User Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.UserStep
   * @generated
   */
  public Adapter createUserStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep <em>System Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.SystemStep
   * @generated
   */
  public Adapter createSystemStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep <em>Repeating Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ucwriter.xtext.guimeta.ucdsl.uCdsl.RepeatingStep
   * @generated
   */
  public Adapter createRepeatingStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //UCdslAdapterFactory
