/**
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.uCdsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import ucwriter.xtext.guimeta.ucdsl.uCdsl.ExtensionStep;
import ucwriter.xtext.guimeta.ucdsl.uCdsl.UCdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Extension Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ucwriter.xtext.guimeta.ucdsl.uCdsl.impl.ExtensionStepImpl#getSentence <em>Sentence</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExtensionStepImpl extends StepImpl implements ExtensionStep
{
  /**
   * The default value of the '{@link #getSentence() <em>Sentence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSentence()
   * @generated
   * @ordered
   */
  protected static final String SENTENCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSentence() <em>Sentence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSentence()
   * @generated
   * @ordered
   */
  protected String sentence = SENTENCE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExtensionStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UCdslPackage.Literals.EXTENSION_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSentence()
  {
    return sentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSentence(String newSentence)
  {
    String oldSentence = sentence;
    sentence = newSentence;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UCdslPackage.EXTENSION_STEP__SENTENCE, oldSentence, sentence));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UCdslPackage.EXTENSION_STEP__SENTENCE:
        return getSentence();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UCdslPackage.EXTENSION_STEP__SENTENCE:
        setSentence((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UCdslPackage.EXTENSION_STEP__SENTENCE:
        setSentence(SENTENCE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UCdslPackage.EXTENSION_STEP__SENTENCE:
        return SENTENCE_EDEFAULT == null ? sentence != null : !SENTENCE_EDEFAULT.equals(sentence);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sentence: ");
    result.append(sentence);
    result.append(')');
    return result.toString();
  }

} //ExtensionStepImpl
