/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import useCase.xtext.useCaseDsl.services.UseCaseDslGrammarAccess;
import useCase.xtext.useCaseDsl.useCaseDsl.MainFlow;
import useCase.xtext.useCaseDsl.useCaseDsl.Step;
import useCase.xtext.useCaseDsl.useCaseDsl.SystemStep;
import useCase.xtext.useCaseDsl.useCaseDsl.UseCase;
import useCase.xtext.useCaseDsl.useCaseDsl.UseCaseDslPackage;
import useCase.xtext.useCaseDsl.useCaseDsl.UserStep;

@SuppressWarnings("all")
public class UseCaseDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private UseCaseDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == UseCaseDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case UseCaseDslPackage.MAIN_FLOW:
				sequence_MainFlow(context, (MainFlow) semanticObject); 
				return; 
			case UseCaseDslPackage.STEP:
				sequence_Step(context, (Step) semanticObject); 
				return; 
			case UseCaseDslPackage.SYSTEM_STEP:
				sequence_SystemStep(context, (SystemStep) semanticObject); 
				return; 
			case UseCaseDslPackage.USE_CASE:
				sequence_UseCase(context, (UseCase) semanticObject); 
				return; 
			case UseCaseDslPackage.USER_STEP:
				sequence_UserStep(context, (UserStep) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     MainFlow returns MainFlow
	 *
	 * Constraint:
	 *     steps+=Step+
	 */
	protected void sequence_MainFlow(ISerializationContext context, MainFlow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Step returns Step
	 *
	 * Constraint:
	 *     ((type=UserStep | type=SystemStep) sentence=Sentence)
	 */
	protected void sequence_Step(ISerializationContext context, Step semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SystemStep returns SystemStep
	 *
	 * Constraint:
	 *     name=INT
	 */
	protected void sequence_SystemStep(ISerializationContext context, SystemStep semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UseCaseDslPackage.Literals.SYSTEM_STEP__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDslPackage.Literals.SYSTEM_STEP__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSystemStepAccess().getNameINTTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     UseCase returns UseCase
	 *
	 * Constraint:
	 *     (number=INT name=ID mainflow=MainFlow)
	 */
	protected void sequence_UseCase(ISerializationContext context, UseCase semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UseCaseDslPackage.Literals.USE_CASE__NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDslPackage.Literals.USE_CASE__NUMBER));
			if (transientValues.isValueTransient(semanticObject, UseCaseDslPackage.Literals.USE_CASE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDslPackage.Literals.USE_CASE__NAME));
			if (transientValues.isValueTransient(semanticObject, UseCaseDslPackage.Literals.USE_CASE__MAINFLOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDslPackage.Literals.USE_CASE__MAINFLOW));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUseCaseAccess().getNumberINTTerminalRuleCall_1_0(), semanticObject.getNumber());
		feeder.accept(grammarAccess.getUseCaseAccess().getNameIDTerminalRuleCall_3_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getUseCaseAccess().getMainflowMainFlowParserRuleCall_4_0(), semanticObject.getMainflow());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     UserStep returns UserStep
	 *
	 * Constraint:
	 *     name=INT
	 */
	protected void sequence_UserStep(ISerializationContext context, UserStep semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UseCaseDslPackage.Literals.USER_STEP__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDslPackage.Literals.USER_STEP__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUserStepAccess().getNameINTTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
