/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.ide;


/**
 * Use this class to register ide components.
 */
public class UseCaseDslIdeModule extends AbstractUseCaseDslIdeModule {
}
