/*
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ucwriter.xtext.guimeta.ucdsl.UCdslRuntimeModule;
import ucwriter.xtext.guimeta.ucdsl.UCdslStandaloneSetup;
import ucwriter.xtext.guimeta.ucdsl.ide.UCdslIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class UCdslWebSetup extends UCdslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UCdslRuntimeModule(), new UCdslIdeModule(), new UCdslWebModule()));
	}
	
}
