/**
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.useCaseDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCaseDslFactory
 * @model kind="package"
 * @generated
 */
public interface UseCaseDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "useCaseDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.useCase/useCaseDsl/UseCaseDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "useCaseDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UseCaseDslPackage eINSTANCE = useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl.init();

  /**
   * The meta object id for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseImpl <em>Use Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseImpl
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getUseCase()
   * @generated
   */
  int USE_CASE = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NAME = 1;

  /**
   * The feature id for the '<em><b>Mainflow</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__MAINFLOW = 2;

  /**
   * The number of structural features of the '<em>Use Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.MainFlowImpl <em>Main Flow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.MainFlowImpl
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getMainFlow()
   * @generated
   */
  int MAIN_FLOW = 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FLOW__STEPS = 0;

  /**
   * The number of structural features of the '<em>Main Flow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FLOW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.StepImpl
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getStep()
   * @generated
   */
  int STEP = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TYPE = 0;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__SENTENCE = 1;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.UserStepImpl <em>User Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UserStepImpl
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getUserStep()
   * @generated
   */
  int USER_STEP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP__NAME = 0;

  /**
   * The number of structural features of the '<em>User Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STEP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.SystemStepImpl <em>System Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.SystemStepImpl
   * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getSystemStep()
   * @generated
   */
  int SYSTEM_STEP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP__NAME = 0;

  /**
   * The number of structural features of the '<em>System Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STEP_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link useCase.xtext.useCaseDsl.useCaseDsl.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCase
   * @generated
   */
  EClass getUseCase();

  /**
   * Returns the meta object for the attribute '{@link useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getNumber()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Number();

  /**
   * Returns the meta object for the attribute '{@link useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getName()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Name();

  /**
   * Returns the meta object for the containment reference '{@link useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getMainflow <em>Mainflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mainflow</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCase#getMainflow()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Mainflow();

  /**
   * Returns the meta object for class '{@link useCase.xtext.useCaseDsl.useCaseDsl.MainFlow <em>Main Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Flow</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.MainFlow
   * @generated
   */
  EClass getMainFlow();

  /**
   * Returns the meta object for the containment reference list '{@link useCase.xtext.useCaseDsl.useCaseDsl.MainFlow#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.MainFlow#getSteps()
   * @see #getMainFlow()
   * @generated
   */
  EReference getMainFlow_Steps();

  /**
   * Returns the meta object for class '{@link useCase.xtext.useCaseDsl.useCaseDsl.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the containment reference '{@link useCase.xtext.useCaseDsl.useCaseDsl.Step#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.Step#getType()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Type();

  /**
   * Returns the meta object for the attribute '{@link useCase.xtext.useCaseDsl.useCaseDsl.Step#getSentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sentence</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.Step#getSentence()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Sentence();

  /**
   * Returns the meta object for class '{@link useCase.xtext.useCaseDsl.useCaseDsl.UserStep <em>User Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Step</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UserStep
   * @generated
   */
  EClass getUserStep();

  /**
   * Returns the meta object for the attribute '{@link useCase.xtext.useCaseDsl.useCaseDsl.UserStep#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.UserStep#getName()
   * @see #getUserStep()
   * @generated
   */
  EAttribute getUserStep_Name();

  /**
   * Returns the meta object for class '{@link useCase.xtext.useCaseDsl.useCaseDsl.SystemStep <em>System Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Step</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.SystemStep
   * @generated
   */
  EClass getSystemStep();

  /**
   * Returns the meta object for the attribute '{@link useCase.xtext.useCaseDsl.useCaseDsl.SystemStep#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see useCase.xtext.useCaseDsl.useCaseDsl.SystemStep#getName()
   * @see #getSystemStep()
   * @generated
   */
  EAttribute getSystemStep_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UseCaseDslFactory getUseCaseDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseImpl <em>Use Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseImpl
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getUseCase()
     * @generated
     */
    EClass USE_CASE = eINSTANCE.getUseCase();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NUMBER = eINSTANCE.getUseCase_Number();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NAME = eINSTANCE.getUseCase_Name();

    /**
     * The meta object literal for the '<em><b>Mainflow</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__MAINFLOW = eINSTANCE.getUseCase_Mainflow();

    /**
     * The meta object literal for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.MainFlowImpl <em>Main Flow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.MainFlowImpl
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getMainFlow()
     * @generated
     */
    EClass MAIN_FLOW = eINSTANCE.getMainFlow();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_FLOW__STEPS = eINSTANCE.getMainFlow_Steps();

    /**
     * The meta object literal for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.StepImpl
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__TYPE = eINSTANCE.getStep_Type();

    /**
     * The meta object literal for the '<em><b>Sentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__SENTENCE = eINSTANCE.getStep_Sentence();

    /**
     * The meta object literal for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.UserStepImpl <em>User Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UserStepImpl
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getUserStep()
     * @generated
     */
    EClass USER_STEP = eINSTANCE.getUserStep();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_STEP__NAME = eINSTANCE.getUserStep_Name();

    /**
     * The meta object literal for the '{@link useCase.xtext.useCaseDsl.useCaseDsl.impl.SystemStepImpl <em>System Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.SystemStepImpl
     * @see useCase.xtext.useCaseDsl.useCaseDsl.impl.UseCaseDslPackageImpl#getSystemStep()
     * @generated
     */
    EClass SYSTEM_STEP = eINSTANCE.getSystemStep();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_STEP__NAME = eINSTANCE.getSystemStep_Name();

  }

} //UseCaseDslPackage
