/**
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.useCaseDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Step</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see useCase.xtext.useCaseDsl.useCaseDsl.UseCaseDslPackage#getUserStep()
 * @model
 * @generated
 */
public interface UserStep extends EObject
{
} // UserStep
