/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UseCaseDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("useCase/xtext/useCaseDsl/parser/antlr/internal/InternalUseCaseDslParser.tokens");
	}
}
