/**
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import ucwriter.xtext.guimeta.ucdsl.AbstractUCdslRuntimeModule;
import ucwriter.xtext.guimeta.ucdsl.useCaseDslIQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UCdslRuntimeModule extends AbstractUCdslRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return useCaseDslIQualifiedNameProvider.class;
  }
}
