/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UseCaseDslRuntimeModule extends AbstractUseCaseDslRuntimeModule {
}
