/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UseCaseDslStandaloneSetup extends UseCaseDslStandaloneSetupGenerated {

	public static void doSetup() {
		new UseCaseDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
