///*
// * generated by Xtext 2.21.0
// */
//package ucwriter.xtext.guimeta.ucdsl.tests
//
//import com.google.inject.Inject
//import org.eclipse.xtext.testing.InjectWith
//import org.eclipse.xtext.testing.extensions.InjectionExtension
//import org.eclipse.xtext.testing.util.ParseHelper
//import org.junit.jupiter.api.Assertions
//import org.junit.jupiter.api.Test
//import org.junit.jupiter.api.^extension.ExtendWith
//import ucwriter.xtext.guimeta.ucdsl.uCdsl.Model
//
//@ExtendWith(InjectionExtension)
//@InjectWith(UCdslInjectorProvider)
//class UCdslParsingTest {
//	@Inject
//	ParseHelper<Model> parseHelper
//	
//	@Test
//	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assertions.assertNotNull(result)
//		val errors = result.eResource.errors
//		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
//	}
//}
