/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UseCaseDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class UseCaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.UseCase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUCKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumberAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumberINTTerminalRuleCall_1_0 = (RuleCall)cNumberAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Assignment cMainflowAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMainflowMainFlowParserRuleCall_4_0 = (RuleCall)cMainflowAssignment_4.eContents().get(0);
		
		//UseCase:
		//	'UC' number=INT ':' name=ID /*QualifiedName suspendo enquanto não resolver bug*/
		//	mainflow=MainFlow;
		@Override public ParserRule getRule() { return rule; }
		
		//'UC' number=INT ':' name=ID /*QualifiedName suspendo enquanto não resolver bug*/ mainflow=MainFlow
		public Group getGroup() { return cGroup; }
		
		//'UC'
		public Keyword getUCKeyword_0() { return cUCKeyword_0; }
		
		//number=INT
		public Assignment getNumberAssignment_1() { return cNumberAssignment_1; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_1_0() { return cNumberINTTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		///*QualifiedName suspendo enquanto não resolver bug*/ mainflow=MainFlow
		public Assignment getMainflowAssignment_4() { return cMainflowAssignment_4; }
		
		//MainFlow
		public RuleCall getMainflowMainFlowParserRuleCall_4_0() { return cMainflowMainFlowParserRuleCall_4_0; }
	}
	public class MainFlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.MainFlow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMainFlowAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMainFlowKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cBEGINTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cStepsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStepsStepParserRuleCall_4_0 = (RuleCall)cStepsAssignment_4.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//MainFlow:
		//	{MainFlow} 'MainFlow' ':'
		//	BEGIN
		//	steps+=Step+
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//{MainFlow} 'MainFlow' ':' BEGIN steps+=Step+ END
		public Group getGroup() { return cGroup; }
		
		//{MainFlow}
		public Action getMainFlowAction_0() { return cMainFlowAction_0; }
		
		//'MainFlow'
		public Keyword getMainFlowKeyword_1() { return cMainFlowKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_3() { return cBEGINTerminalRuleCall_3; }
		
		//steps+=Step+
		public Assignment getStepsAssignment_4() { return cStepsAssignment_4; }
		
		//Step
		public RuleCall getStepsStepParserRuleCall_4_0() { return cStepsStepParserRuleCall_4_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_5() { return cENDTerminalRuleCall_5; }
	}
	public class StepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.Step");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStepAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeAlternatives_1_0 = (Alternatives)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeUserStepParserRuleCall_1_0_0 = (RuleCall)cTypeAlternatives_1_0.eContents().get(0);
		private final RuleCall cTypeSystemStepParserRuleCall_1_0_1 = (RuleCall)cTypeAlternatives_1_0.eContents().get(1);
		private final Assignment cSentenceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSentenceSentenceParserRuleCall_2_0 = (RuleCall)cSentenceAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Step:
		//	{Step} type=(UserStep | SystemStep /*|ExtensionStep*/) sentence=Sentence ';';
		@Override public ParserRule getRule() { return rule; }
		
		//{Step} type=(UserStep | SystemStep /*|ExtensionStep*/) sentence=Sentence ';'
		public Group getGroup() { return cGroup; }
		
		//{Step}
		public Action getStepAction_0() { return cStepAction_0; }
		
		//type=(UserStep | SystemStep /*|ExtensionStep*/)
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//(UserStep | SystemStep /*|ExtensionStep*/)
		public Alternatives getTypeAlternatives_1_0() { return cTypeAlternatives_1_0; }
		
		//UserStep
		public RuleCall getTypeUserStepParserRuleCall_1_0_0() { return cTypeUserStepParserRuleCall_1_0_0; }
		
		//SystemStep
		public RuleCall getTypeSystemStepParserRuleCall_1_0_1() { return cTypeSystemStepParserRuleCall_1_0_1; }
		
		//sentence=Sentence
		public Assignment getSentenceAssignment_2() { return cSentenceAssignment_2; }
		
		//Sentence
		public RuleCall getSentenceSentenceParserRuleCall_2_0() { return cSentenceSentenceParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class UserStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.UserStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUserStepAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameINTTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUserKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//UserStep:
		//	{UserStep} name=INT '.' 'User';
		@Override public ParserRule getRule() { return rule; }
		
		//{UserStep} name=INT '.' 'User'
		public Group getGroup() { return cGroup; }
		
		//{UserStep}
		public Action getUserStepAction_0() { return cUserStepAction_0; }
		
		//name=INT
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//INT
		public RuleCall getNameINTTerminalRuleCall_1_0() { return cNameINTTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//'User'
		public Keyword getUserKeyword_3() { return cUserKeyword_3; }
	}
	public class SystemStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.SystemStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSystemStepAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameINTTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSystemKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SystemStep:
		//	{SystemStep} name=INT '.' 'System';
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemStep} name=INT '.' 'System'
		public Group getGroup() { return cGroup; }
		
		//{SystemStep}
		public Action getSystemStepAction_0() { return cSystemStepAction_0; }
		
		//name=INT
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//INT
		public RuleCall getNameINTTerminalRuleCall_1_0() { return cNameINTTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//'System'
		public Keyword getSystemKeyword_3() { return cSystemKeyword_3; }
	}
	public class SentenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.Sentence");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		///************************** V 0.2 **************************************************** 
		//ExtensionStep:
		//	(startAt = [Step]) '.' name = CHAR '.';
		//
		//Extension:
		//	{Extension} 'AlternativeFlow:'
		//	BEGIN
		//		(steps += Step)*
		//	END;
		//***************************************************************************************/ /********************	
		//*******DataTypes*****
		//*********************/ /* Incrivelmente não consigo fazer isso funcionar como eu quero, não consigo colocar espaços entre os IDs
		// * //This QualifiedName allows to create a name like: buying things nice
		//QualifiedName:
		//	ID (Strangeerro);
		///* Strange errors that I can't make an long name with any number o WS and IDs// 
		//Strangeerro:
		//	(ANY_OTHER|WS)* (ID)*
		//;	
		//*/ //Bug: preciso nao capturar as palavras
		//Sentence:
		//	STRING*;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING*
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	
	private final UseCaseElements pUseCase;
	private final MainFlowElements pMainFlow;
	private final StepElements pStep;
	private final UserStepElements pUserStep;
	private final SystemStepElements pSystemStep;
	private final SentenceElements pSentence;
	private final TerminalRule tCHAR;
	private final TerminalRule tBEGIN;
	private final TerminalRule tEND;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UseCaseDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUseCase = new UseCaseElements();
		this.pMainFlow = new MainFlowElements();
		this.pStep = new StepElements();
		this.pUserStep = new UserStepElements();
		this.pSystemStep = new SystemStepElements();
		this.pSentence = new SentenceElements();
		this.tCHAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.CHAR");
		this.tBEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.BEGIN");
		this.tEND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "useCase.xtext.useCaseDsl.UseCaseDsl.END");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("useCase.xtext.useCaseDsl.UseCaseDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//UseCase:
	//	'UC' number=INT ':' name=ID /*QualifiedName suspendo enquanto não resolver bug*/
	//	mainflow=MainFlow;
	public UseCaseElements getUseCaseAccess() {
		return pUseCase;
	}
	
	public ParserRule getUseCaseRule() {
		return getUseCaseAccess().getRule();
	}
	
	//MainFlow:
	//	{MainFlow} 'MainFlow' ':'
	//	BEGIN
	//	steps+=Step+
	//	END;
	public MainFlowElements getMainFlowAccess() {
		return pMainFlow;
	}
	
	public ParserRule getMainFlowRule() {
		return getMainFlowAccess().getRule();
	}
	
	//Step:
	//	{Step} type=(UserStep | SystemStep /*|ExtensionStep*/) sentence=Sentence ';';
	public StepElements getStepAccess() {
		return pStep;
	}
	
	public ParserRule getStepRule() {
		return getStepAccess().getRule();
	}
	
	//UserStep:
	//	{UserStep} name=INT '.' 'User';
	public UserStepElements getUserStepAccess() {
		return pUserStep;
	}
	
	public ParserRule getUserStepRule() {
		return getUserStepAccess().getRule();
	}
	
	//SystemStep:
	//	{SystemStep} name=INT '.' 'System';
	public SystemStepElements getSystemStepAccess() {
		return pSystemStep;
	}
	
	public ParserRule getSystemStepRule() {
		return getSystemStepAccess().getRule();
	}
	
	///************************** V 0.2 **************************************************** 
	//ExtensionStep:
	//	(startAt = [Step]) '.' name = CHAR '.';
	//
	//Extension:
	//	{Extension} 'AlternativeFlow:'
	//	BEGIN
	//		(steps += Step)*
	//	END;
	//***************************************************************************************/ /********************	
	//*******DataTypes*****
	//*********************/ /* Incrivelmente não consigo fazer isso funcionar como eu quero, não consigo colocar espaços entre os IDs
	// * //This QualifiedName allows to create a name like: buying things nice
	//QualifiedName:
	//	ID (Strangeerro);
	///* Strange errors that I can't make an long name with any number o WS and IDs// 
	//Strangeerro:
	//	(ANY_OTHER|WS)* (ID)*
	//;	
	//*/ //Bug: preciso nao capturar as palavras
	//Sentence:
	//	STRING*;
	public SentenceElements getSentenceAccess() {
		return pSentence;
	}
	
	public ParserRule getSentenceRule() {
		return getSentenceAccess().getRule();
	}
	
	//terminal CHAR:
	//	'a'..'z' | 'A'..'Z';
	public TerminalRule getCHARRule() {
		return tCHAR;
	}
	
	//terminal BEGIN:
	//	'synthetic:BEGIN';
	public TerminalRule getBEGINRule() {
		return tBEGIN;
	}
	
	//terminal END:
	//	'synthetic:END';
	public TerminalRule getENDRule() {
		return tEND;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
