/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUseCaseDslScopeProvider extends DelegatingScopeProvider {
}
