/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UseCaseDslUiModule extends AbstractUseCaseDslUiModule {

	public UseCaseDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
