/**
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import ucwriter.xtext.guimeta.ucdsl.tests.UCdslInjectorProvider;
import ucwriter.xtext.guimeta.ucdsl.uCdsl.UseCaseDocument;

@ExtendWith(InjectionExtension.class)/* 
@InjectWith(UCdslInjectorProvider.class) */
public class UCdslParsingTest {
  @Inject
  private /* ParseHelper<UseCaseDocument> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field UCdslParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
