/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import useCase.xtext.useCaseDsl.ui.internal.UseCaseDslActivator;

public class UseCaseDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UseCaseDslActivator.getInstance().getInjector("useCase.xtext.useCaseDsl.UseCaseDsl");
	}

}
