/*
 * generated by Xtext 2.21.0
 *
package ucwriter.xtext.guimeta.ucdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 *
public class UCdslRuntimeModule extends AbstractUCdslRuntimeModule {
}*/
