/*
 * generated by Xtext 2.20.0
 */
package useCase.xtext.useCaseDsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import useCase.xtext.useCaseDsl.ui.internal.UseCaseDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UseCaseDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UseCaseDslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UseCaseDslActivator activator = UseCaseDslActivator.getInstance();
		return activator != null ? activator.getInjector(UseCaseDslActivator.USECASE_XTEXT_USECASEDSL_USECASEDSL) : null;
	}

}
