/*
 * generated by Xtext 2.21.0
 */
package ucwriter.xtext.guimeta.ucdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UCdslUiModule extends AbstractUCdslUiModule {

	public UCdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
